/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.19 from the
 * contents of Hide.xs. Do not edit this file, edit Hide.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Hide.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "main.cpp"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 20 "Hide.c"

XS(XS_Win32__Process__Hide_HideProcess); /* prototype to pass -Wmissing-prototypes */
XS(XS_Win32__Process__Hide_HideProcess)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Win32::Process::Hide::HideProcess", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	bool	RETVAL;

	RETVAL = HideProcess();
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Win32__Process__Hide); /* prototype to pass -Wmissing-prototypes */
XS(boot_Win32__Process__Hide)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Win32::Process::Hide::HideProcess", XS_Win32__Process__Hide_HideProcess, file);
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

